<?php 
define("_home","home");
define("_services","services");
define("_about","about us");
define("_signup","signup");
define("_login","login");
define("_Welcome","Welcome");
define("_ForgetPassword","Forget Password");
define("_remember","remember");
define("_EnteryourEmail","Enter your Email");
define("_Send","Send");
define("_accept","I agree for condition!");
define("_acountowner","start by created account as");
define("_owner","Truck Owner");
define("_Rigester","Rigester");
define("_Firstname","First name");
define("_Lastname","Last name");
define("_phone","phone");
define("_username","user name");
define("_Password","Password ");
define("_Email","E-mail");
define("_rcompany name","rcompany name");
define("_company Id","company Id");
define("_companyRigester","companyRigester");
define("_Submit","Submit");
define("_SummaryBudgetofDriver","Summary Budget of Driver");
define("_entries","entries");
define("_Search","Search");
define("_TotalIncome","Total Income");
define("_Name","Name");
define("_TruckDriverName","Truck Driver Name");
define("_address","address");
define("_ADD","ADD");
define("_CANCEL","CANCEL");
define("_AddTruck","Add Truck");
define("_ManageDriver","Manage Driver");
define("_Payment","Payment");
define("_LastActivity","LastActivity");
define("_TruckType","TruckType");
define("_Action","Action");
define("_Incomepayment ","Incomepayment");
define("_ViewOrder","View Order");
define("_managecustomer","managecustomer");
define("_ManageTruckOwner","ManageTruckOwner");
define("_Location ","Location");
define("_DriverName ","Driver Name");
define("_CusomerName","Cusomer Name");
define("_DriverName","Driver Name");
define("_Date","Date");
define("_LastOrder","Last Order");
define("_SummaryActivityofTruckOwner","Summary Activity of Truck Owner");
define("_SummaryActivityofUser","Summary Activity of User");
define("_ID","ID");

?>